#!/usr/bin/env python3
"""Harden formula-atlas source identity without changing generated bytes."""

from __future__ import annotations

from pathlib import Path


BUILD = Path("scripts/build_formula_atlas.py")
TEST = Path("tests/test_formula_quant_atlas.py")
SOURCE_SHA256 = "c0b6dfee3233097307c518a57c076e5ba3ea9013f34ab454bef92aeddf0f3634"
SOURCE_GIT_BLOB_SHA = "600654f89cb062320acae4284cb5220ff881eb3c"


def replace_once(source: str, old: str, new: str, label: str) -> str:
    count = source.count(old)
    if count != 1:
        raise SystemExit(f"{label} drifted: expected one target, found {count}")
    return source.replace(old, new, 1)


def patch_build() -> None:
    source = BUILD.read_text(encoding="utf-8")
    source = replace_once(
        source,
        '    "state": "ARCHIVED_ATTRIBUTED_SOURCE",\n}\nALLOWED_CLASSES = {\n',
        '    "state": "ARCHIVED_ATTRIBUTED_SOURCE",\n}\n'
        f'SOURCE_SHA256 = "{SOURCE_SHA256}"\n'
        'ALLOWED_CLASSES = {\n',
        "source digest constant",
    )
    source = replace_once(
        source,
        '\n\ndef admission_for(record_class: str) -> str:\n',
        '\n\ndef git_blob_sha(raw: bytes) -> str:\n'
        '    """Return Git\'s exact object identity for one blob."""\n\n'
        '    header = f"blob {len(raw)}\\0".encode("ascii")\n'
        '    return hashlib.sha1(header + raw, usedforsecurity=False).hexdigest()\n\n\n'
        'def admission_for(record_class: str) -> str:\n',
        "Git blob helper",
    )
    source = replace_once(
        source,
        'def build(source_path: Path) -> dict[str, Any]:\n'
        '    raw = source_path.read_bytes()\n'
        '    source = json.loads(raw)\n',
        'def build(source_path: Path) -> dict[str, Any]:\n'
        '    raw = source_path.read_bytes()\n'
        '    observed_sha256 = hashlib.sha256(raw).hexdigest()\n'
        '    if observed_sha256 != SOURCE_SHA256:\n'
        '        raise ValueError("vendored formula corpus SHA-256 drift")\n'
        '    observed_git_blob_sha = git_blob_sha(raw)\n'
        '    if observed_git_blob_sha != SOURCE["git_blob_sha"]:\n'
        '        raise ValueError("vendored formula corpus Git blob identity drift")\n'
        '    source = json.loads(raw)\n',
        "source identity admission",
    )
    source = replace_once(
        source,
        '            "sha256": hashlib.sha256(raw).hexdigest(),\n',
        '            "sha256": observed_sha256,\n',
        "source digest emission",
    )
    BUILD.write_text(source, encoding="utf-8")


def patch_test() -> None:
    source = TEST.read_text(encoding="utf-8")
    source = replace_once(
        source,
        'ATLAS = ROOT / "atlas" / "formula-atlas.v1.json"\n',
        'ATLAS = ROOT / "atlas" / "formula-atlas.v1.json"\n'
        f'SOURCE_SHA256 = "{SOURCE_SHA256}"\n'
        f'SOURCE_GIT_BLOB_SHA = "{SOURCE_GIT_BLOB_SHA}"\n'
        'PACKAGE_ATLASES = (\n'
        '    ROOT / "torch-ext" / "szl_formulas" / "formula_atlas.v1.json",\n'
        '    ROOT / "build" / "torch-universal" / "szl_formulas" / "formula_atlas.v1.json",\n'
        ')\n',
        "test source constants",
    )
    source = replace_once(
        source,
        '    assert atlas["source"]["git_blob_sha"] == "600654f89cb062320acae4284cb5220ff881eb3c"\n'
        '    assert atlas["source"]["sha256"] == hashlib.sha256(SOURCE.read_bytes()).hexdigest()\n',
        '    raw = SOURCE.read_bytes()\n'
        '    assert atlas["source"]["git_blob_sha"] == SOURCE_GIT_BLOB_SHA\n'
        '    assert atlas["source"]["sha256"] == SOURCE_SHA256\n'
        '    assert hashlib.sha256(raw).hexdigest() == SOURCE_SHA256\n'
        '    git_object = f"blob {len(raw)}\\0".encode("ascii") + raw\n'
        '    assert (\n'
        '        hashlib.sha1(git_object, usedforsecurity=False).hexdigest()\n'
        '        == SOURCE_GIT_BLOB_SHA\n'
        '    )\n',
        "test source identity",
    )
    source = replace_once(
        source,
        '\n\ndef test_locked_eight_remains_separate_from_all_status_strings() -> None:\n',
        '\n\ndef test_packaged_atlases_match_canonical_bytes() -> None:\n'
        '    for packaged in PACKAGE_ATLASES:\n'
        '        assert packaged.read_bytes() == ATLAS.read_bytes()\n\n\n'
        'def test_builder_rejects_vendored_source_drift() -> None:\n'
        '    with tempfile.TemporaryDirectory() as temporary:\n'
        '        directory = Path(temporary)\n'
        '        mutated = directory / "mutated-source.json"\n'
        '        output = directory / "atlas.json"\n'
        '        mutated.write_bytes(SOURCE.read_bytes() + b"\\n")\n'
        '        completed = subprocess.run(\n'
        '            [\n'
        '                sys.executable,\n'
        '                str(ROOT / "scripts" / "build_formula_atlas.py"),\n'
        '                "--source",\n'
        '                str(mutated),\n'
        '                "--output",\n'
        '                str(output),\n'
        '            ],\n'
        '            check=False,\n'
        '            capture_output=True,\n'
        '            text=True,\n'
        '        )\n'
        '        assert completed.returncode != 0\n'
        '        assert not output.exists()\n'
        '        assert "vendored formula corpus SHA-256 drift" in completed.stderr\n\n\n'
        'def test_locked_eight_remains_separate_from_all_status_strings() -> None:\n',
        "provenance regression tests",
    )
    TEST.write_text(source, encoding="utf-8")


def main() -> int:
    patch_build()
    patch_test()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
